# Terraform Provider test workflow.
name: Test

# This GitHub action creates launch test when a commit is done 
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
          go-version-file: './go.mod'
      - run: go mod tidy
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
          go-version-file: './go.mod'
      - run: go test -v -tags=unit_tests ./... 
